### ISSUE TITLE
Invoice reminder bad translation

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1053]
Hello,
In the settings of the payment reminder option for invoices (settings-notification-invoice-invoice reminder), all the shops have the French translation. This is the text I want it to be sent. However, when we send the reminder of invoices to pay (manage the invoice-selected-action: sent the reminder), the text is in English. This is the default text. Magré the fact that it is confirguré in French, customers receive it in English.

--
<img width="930" alt="translation in invoice reminder" src="https://user-images.githubusercontent.com/40500094/75195747-85018880-5728-11ea-8868-1a8e34e7e0f5.png">

French:
Bonjour,
Dans les réglages de l'option de rappel de paiement pour factures (réglages-notification-facture-rappel de facture), toutes les boutiques ont la traducton Francaise. Il s'agit du texte que je souhaite qu'il soit envoyé. Cependant, lorsque nous envoyons les rappel de factures à payer (gérer les facture-sélectionné-action: envoyé le rappel), le texte est en anglais. Il s'agit du texte par défaut. Magré le fait qu'il soit confirguré en francais, les clients le recoivent en anglais.

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Thanks

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-918

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

![image](https://user-images.githubusercontent.com/39614480/75319292-3110b400-588e-11ea-8ec2-c93e5827e58b.png)


Thanks!
Usman ali

**Comment by JessicaSOS** [comment]
Hello,
# 1053 is indeed corrected, thank you. however, the # 463 reporter on October 3, 2018 and the # 706 reporter on March 7, 2019 (to name a few), still doesn't work. See the full summary in the new issue: Resume of due invice reminder problem # 1122
