### ISSUE TITLE
Serial Number and Inventory Count 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1164]
Hello, 
The following issues having being going on for the past 1 year. I have spoken to different reps including fahad about the following issues and it seem that unless you guys can't replicated them they don't exist. I have taken video of just 1 inventory count out of the whole year to show you what inventory count is like in my store and to show you how many error in the inventory count happen during just 1 inventory count. As shown in the videos serial numbers are incorrect, serial number don't exits in our inventory and they have never being used on a repair, our inventory is either short or over and serial number when counted aren't auto select from the inventory count system. Im hoping that with the videos that I have recorded just from 1 day it will be enough for you guys to have this issue resolved in a timely manner. 

Ive sent the videos to: fahadimran85@gmail.com

**Comment by Omar1892** [comment]
the issue still happening inventory isn't being display correctly. After doing the inventory count as shown in the videos from last week, we haven't received any new inventory and the inventory still coming up short. I have both serial number on hand, but it inventory says that I only have 1 item in stock. 
![Screen Shot 2020-06-03 at 3 30 40 PM](https://user-images.githubusercontent.com/47898011/83695858-d0d98e80-a5af-11ea-9e3c-a27ba103c880.png)

**Comment by jawad-Repairdesk** [comment]
Hello @Omar1892 ,

We have a discussion with Fahad, he has a meeting with you tomorrow. We hope so we will track the root cause so that you will not face it next time.

Thanks for the patience and time.

**Comment by Omar1892** [comment]
Hello, 

We are really busy to the point that I can't take any calls at the moment. Like I have said, the issue can't be replicated and I don't know how it happens. I sent all the videos to show you guys how it happens so that you guys can try to find the root of the issue. If fahad calls me I don't see how that will change anything since I have already explain this issue multiple times in the past and it hasn't gotten it fixed. If you feel like we are causing the issue im going to explain how things are done in my business because we are definitely we are not the issue and im 100% of it. 

1. Inventory count is due every week. I counted the inventory once every week. 
2. All merchandize is serialized and when a repair is booked in we check the ticket so that we can grab the right serial number. 
3. All new inventory before it arrives to the store is entered in to the system via a P.O
4. All serial numbers are created in the GRN 
5. All inventory before is entered in to the system is carefully counted
6. once we do inventory count the following week theirs always mistake in the qualities or serial numbers from the previous P.O
7. As you seen on the video most serial number don't have any history of ever being used or the inventory is missing with out any explanation. 
8. Its only 2 people working in the store all the time and its me and my business partner so no one is stilling the inventory.

My believe is that the issue is coming from the P.O because before we were using the P.O to enter the inventory we were manually entering it. And this issue never happened. I believe that once the inventory in entered through the P.O the inventory mess-up.

**Comment by Omar1892** [comment]
I have shared a new videos of other issues that are related to the issues that im experiencing. I sent the videos to Adnan Cheema

**Comment by jawad-Repairdesk** [comment]
Alright, let me review it with Adnan and get back to you. Sorry for the inconvenience.

**Comment by Omar1892** [comment]
This error was just found yesterday. 

![Screen Shot 2020-06-09 at 9 18 05 AM](https://user-images.githubusercontent.com/47898011/84173899-bfbad280-aa32-11ea-96a5-2c8763a6a611.png)

**Comment by Omar1892** [comment]
This was just found yesterday. 


![Screen Shot 2020-06-09 at 9 18 05 AM](https://user-images.githubusercontent.com/47898011/84174022-e842cc80-aa32-11ea-9a98-b1bfae2460eb.png)

**Comment by Omar1892** [comment]
@usmanalikhan93 do you have any updates on the issue? or when it will be resolved by? The issue still continuing to happen.

**Comment by usmanalikhan93** [comment]
@jawad-Repairdesk FYI

**Comment by jawad-Repairdesk** [comment]
Hello @Omar1892 ,

Sorry for the trouble, we have sorted out the issue and found the scenario how it was produced. Although the issue had been resolved but it is not possible for us to clear the data anomaly that had been produced. I will have to take a review of your inventory so that we could make it clear once for every possible scenario. 
We hope after that you will not face this type of issue again.

Thanks

**Comment by Omar1892** [comment]
@jawad-Repairdesk Thank you! How long will this process take?

**Comment by Omar1892** [comment]
@jawad-Repairdesk Thank you! How long will this process take?

**Comment by jawad-Repairdesk** [comment]
Hi @Omar1892 ,

I hope you had a discussion with Fahad, I had reviewed your inventory and unable to find the root cause because it has been updated already. and some of your reference inventory had already been deleted. 

For now i think we should close it. But i have informed Fahad to keep in touch with you, if you face any issue in inventory please let us know so we can find out the reason. We have resolved one issue that produces the issue. But if still there is an issue, we will try to resolve it. 
Thanks

**Comment by Omar1892** [comment]
@jawad-Repairdesk I have had this issue for the past 1 year and for you not to find the issue is just not right. I can't not leave unfixed the inventory because the issues will end up buying more inventory or making mistakes on our inventory. I want to speak to a manager because I sent you like 10 videos and for you to tell me that you can't fix it its just a joke!!!

**Comment by jawad-Repairdesk** [comment]
Hi @Omar1892 ,
I have tested it and found one issue that has already been resolved. After its resolution it will not produce with that scenario. That is why inform Fahad to contact you and to inform you that if you find the issue again please let us know the inventory. That inventory help us to find that particular case that has left (if any). 

Please contact Fahad for the details. We had a long discussion on your issue. I hope you will not face this type of issue again. 

Another thing i need to share with you. Please have a call with Fahad and tell him about your workflow it helps to create your scenarios in QA environment that will help us to test better with respect to customer's perspective. 

I am really sorry for the trouble and miscommunication between us.

Thanks

**Comment by Omar1892** [comment]
Hello, don’t close it yet. I’ll close it when I see this issue not replicating in my inventory.

**Comment by Omar1892** [comment]
It’s just a matter of days or hours for it to show again. It already did this morning, and fahad has seen it as well. So the issue is till there.

**Comment by jawad-Repairdesk** [comment]
Dear @Omar1892 ,
Issue has been resolved but if the inventory that had already been disturbed due to that could not correct automatically.

I have dropped a message to Fahad and will check either the issue is same with that particular inventory item or not and please share the inventory id or name so i can look into it for you. 

Thanks

**Comment by Omar1892** [comment]
Hello, 

just to be sure that you know. We are still having the same issue in the store. Fahad told me that you guys are working on a permeant solution.

**Comment by Omar1892** [comment]
@jawad-Repairdesk 

Hello,

just to be sure that you know. We are still having the same issue in the store. Fahad told me that you guys are working on a permeant solution.
