### ISSUE TITLE
No UniqueNess on SKU when do Clone

### ISSUE THREAD

**Issue by BharatPRC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1184]
Hi !
Some products are saved under separate Product ID but with same SKU code.
![2020-06-22_0240](https://user-images.githubusercontent.com/34261339/85230194-de0ccf00-b431-11ea-8658-6ec074e3ecf9.png)

I have noticed , it is happening when we use CLONE option to create new product.
SKU should change automatically when Uniquenss trigger is on.
![2020-06-22_0239](https://user-images.githubusercontent.com/34261339/85230199-e402b000-b431-11ea-993a-ebee0a65747e.png)

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can you please check and verify this?

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-1423

**Comment by usmanalikhan93** [comment]
Hi @BharatPRC 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by BharatPRC** [comment]
Not fixed yet.
Now it is just showing that sku is same , but it doesn't generate a new one automatially

**Comment by usmanalikhan93** [comment]
Hi @BharatPRC 

I hope you are doing well. When you clone item it replicated all the information from it. You just need to clear the SKU field and save it. It will generate new Unique SKU for that clone item. Please check at your end. 

Thanks
Usman Ali

**Comment by BharatPRC** [comment]
Yes , its working that way.
thanks
