### ISSUE TITLE
Selecting print barcodes in GRN with serialized inventory does not work

### ISSUE THREAD

**Issue by mathchouinard** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1285]
When using a serialized inventory, and on the GRN page, selecting all items and then pressing the print barcode button to print all barcodes does not print the serialized inventory label, but rather the regular inventory label. Clicking the print button next to every time prints the serialized inventory label, but is annoying to do for every single item.

**Comment by usmanalikhan93** [comment]
Hey @mathchouinard 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hello @mathchouinard 

I hope you are doing well. I have checked your issue but it seems like it is working fine. Can you please check this video and do let me know if you are following the same steps or not. 
Video link: https://drive.google.com/file/d/1Jx0uM2dW8qich41ot-fbcOqJ9oNQUrMz/view

Thanks 
Usman Ali

**Comment by mathchouinard** [comment]
I believed it was because it was using the inventory label, I was wrong, but there is something different depending on which you choose. if I select them and press the "Print barcode" button, I get this: 
![image](https://user-images.githubusercontent.com/59777705/91383310-d682f100-e7f9-11ea-8470-1484165035d0.png)
Instead, if I press the print button, I get this: 
![image](https://user-images.githubusercontent.com/59777705/91383346-e7336700-e7f9-11ea-9f1a-80015e307835.png)
Why are the barcodes and writing not in the same spots ?

**Comment by usmanalikhan93** [comment]
Hello @mathchouinard 

I hope you are doing well. Can you please reach out to live chat and share some information as required with them ? So I can look further in your account.

**Comment by usmanalikhan93** [comment]
Hello @mathchouinard 

I hope you are doing well. I have received your information from Danish. I will check your query and update you accordingly. 

Thanks,
Usman Ali

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-1724

**Comment by usmanalikhan93** [comment]
Hi @mathchouinard 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by mathchouinard** [comment]
@usmanalikhan93 Hi, while it is better, it is not quite fixed yet.  The space at the top is not the same. I have modified my template because thwhen I press the "Print barcode" button, text would not print fully, as dymo cuts off some text. 
To fix it, I added padding and now both print fully, but I now have this problem. 
When I press "Print barcode", here is what it gives:
![image](https://user-images.githubusercontent.com/59777705/93823679-3cfc0300-fc30-11ea-9f77-7dc2bea73b71.png)
When I press the print button, here is what it gives:
![image](https://user-images.githubusercontent.com/59777705/93824061-d62b1980-fc30-11ea-81a1-1a3f26e691c9.png)

This seems to be because of the added space at the top when using the print button, but is not there when using the "Print barcode".

Thannk you
