### ISSUE TITLE
tradein item when is transfered by inventory transfert

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1407]
We can see the full history of the trade-in item that has been transferred to another store (its transfer, modifications, etc.) but not its sale! The status "sold" is set correctly, but we are not able to visualize in which invoice it was sold. See SOS Phone Lévis trade-in item # 13625, # 13601.

Thank you

_----French:

Nous pouvons apercevoir l'historique complet de l'item trade-in qui a été transféré dans une autre boutique (son transfert ses modifications, etc.) mais pas sa vente! Le statut "sold" se met correctement, mais nous ne sommes pas en mesure de visualisé dans quelle facture il a été vendu. Voir SOS Phone Lévis trade-in item #13625, #13601.

Merci_

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Regards,
M Adnan

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-2090

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have questions.

Thanks! &  Regards,
M Adnan

**Comment by JessicaSOS** [comment]
Did you test something? I can't see the refurbrish tickets that were created for the trade-in item, nor the invoices in which the items were sold.

**Not fixed, please reopen!**

**Comment by Uzair-RepairDesk** [comment]
@Repairdesk-QA 
Please check and verify it

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
I hope you are doing well. Sorry for the trouble. We have resolved the issue and It's working fine with new Trade-Ins items sold. For old Trade-in items sold, you can view invoice numbers and further details from the Trade-in report.
I hope it helps. If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan

**Comment by JessicaSOS** [comment]
I can't see the refurbrish tickets that were created for the trade-in item, but for invoices it has been fixed.

**Comment by Uzair-RepairDesk** [comment]
@Repairdesk-QA
