### ISSUE TITLE
Sales Summary Report only work at selected store

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#383]
It's been a while but I want this issue fixed so I don't have to jump across stores to have this report done.

Basically this report allows me to select stores, but it only works at the selected store. If I select other stores, the report is always $0.00. 

It must have some settings that does not access data from other stores. But the payroll works, so I guess it can be done. Otherwise, there is no meaning for multi store selection.

**Comment by quangc** [comment]
![screen shot 2018-07-26 at 12 47 20 pm](https://user-images.githubusercontent.com/22993605/43238659-71c8bb9e-90d2-11e8-8fc6-f68c00a7627d.png)

**Comment by usmanalikhan93** [comment]
Hey @quangc  👋 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

Usman Ali

**Comment by usmanalikhan93** [comment]
Hey @quangc ,

Just an update we have fixed reported issue and it’s available for beta testing on sandbox server. We are hoping to go live with this either today or tomorrow hopefully.

Thanks
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @quangc ,

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by quangc** [comment]
This one is still having issues. When I select other stores, the system then filtered all staffs for that store, then I will select 1 staff, then date range, then search. The system then display the results and then refresh back to the original store, not keeping the selected store in the filter area.

**Comment by usmanalikhan93** [comment]
Hey @quangc ,
 
Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Usman Ali

**Comment by Repair-Desk** [comment]
**Hey @quangc** 

Sorry for the delay.

We're re-writing our reports module and your feedback will surely be accommodated. 

Also want to share a quick snapshot of Multi-Store sales report that will be rolled out hopefully next week and we will use similar layout for upcoming reports.

![multi-store-sales-report-updated 1](https://user-images.githubusercontent.com/21986026/45450242-1033bd80-b6f1-11e8-8c34-010852d988d9.jpg)

I'll close this task for now.

Regards,
Usman Butt
