### ISSUE TITLE
Sync woo commerce with repairdesk

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#400]
Hello,
Here is a problem that is destroying our lives on a daily basis and has been postponed since at least January 8, 2018 (and maybe even before). We are still without news and the problem is still present. All the phones that are on sale on our website have almost all been sold already. The synchronization between repairdesk and woocommerce is not done correctly. I do not know how often it is, but we must always pay back the customers who buy online because our phones have been sold meanwhile in store.

I tried to add the webhook "product.updated", but it does not correct anymore. You can look at examples with almost all products on sale on our website. They were all created in Repairdesk. This is the email I sent to Ali on January 8, 2018 regarding this problem:

Hi Ali,
Happy New Year to you !
It seems to have an error with the timing of phones to sell. Item xxx8679 was sold on December 13 but continued to be posted on our website. A customer bought it on January 4th. Almost 3 weeks later. Look at the attachments. Can you check what is the problem with sycronization?

![xxx8679](https://user-images.githubusercontent.com/40500094/43799009-404cd1b8-9a5a-11e8-9945-8ef41ceb5ba4.jpg)
![woocommerce xxx8679](https://user-images.githubusercontent.com/40500094/43799016-43e85a04-9a5a-11e8-9c02-2384dac92e88.jpg)

--
french:
Bonjour,
Voici un problème qui nous polue la vie quotidiennement et qui est reporter depuis au moins le 8 janvier 2018 (et peut-être même avant). Nous sommes toujours sans nouvelle et le problème est encore présent. Tous les téléphones qui sont en vente sur notre site internet ont presque tous déjà été vendu. La synchronisation entre repairdesk et woocommerce ne s'effectue pas correctement. J'ai tenté d'ajouter le webhook "product.updated", mais sa ne corrige pas plus. Vous pouvez regarder des exemple avec presque tous les produits en vente sur notre site internet. Ils ont tous été créé dans Repairdesk. Voici le courriel que j'avais envoyé à Ali le 8 janvier 2018 concernant ce problème:

Bonjour Ali,
Bonne année à toi !
Il semble avoir une erreur avec la synchronisation des téléphones à vendre. L'item xxx8679 à été vendu le 13 décembre mais a continué d'être afficher sur notre site internet. Un client l'a donc acheter le 4 janvier. Soit presque 3 semaines plus tard. Regarde les pièce jointe. Peux-tu vérifier quel est le problème avec la sycronisation?__

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali.

**Comment by JessicaSOS** [comment]
**It is not fixed. Thank you to compare the two results**

**What we have in stock in repairdesk:**
https://app.repairdesk.co/index.php?r=inventory%2Ftradein&page=&ids=&Inventory%5Bitem_no%5D=&Inventory%5Bname%5D=&Inventory%5Btradein_id%5D=&Inventory%5Bimei%5D=&Inventory%5Bserial%5D=&Inventory%5Bmanufacturer%5D=&Inventory%5Bdevice%5D=&Inventory%5Bnetwork%5D=&Inventory%5Bcond%5D=&seller=&Inventory%5Bseller%5D=&buyer=&Inventory%5Bbuyer%5D=&Inventory%5Bsale_status%5D=In+Stock&Inventory%5Bcreated_on%5D%5B0%5D=&Inventory%5Bcreated_on%5D%5B1%5D=


**Compared to what is posted on our website:**
https://sosphone.ca/cellulaires-usages/

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Let us check again this.

**Comment by JessicaSOS** [comment]
Thank you for doing your best to solve this problem quickly.

**Comment by JessicaSOS** [comment]
I do not test yet if it works during the sale, but if we put the status "in stock", the item goes online. However if we remove this status to put another, it continues to be visible and "in stock" on our website.

--

French:

Je n'ai pas tester encore si cela fonctionne lors de la vente, mais si nous mettons le status "in stock", l'item se met en ligne. Cependant si nous retirons ce status pour en mettre un autre, il continu d'être visible et "in stock" sur notre site internet.

 

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 24 août 2018 01:41
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Sync woo commerce with repairdesk (#400)

 

Closed #400 <https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/issues/400> .

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Please find developer feedback:- 

"Trade in items only synced when they are in stock or when they are sold. after sale it doesn't synced with WC. as i said earlier there was a bug when trade in item sold on repairdesk it doesn't update it on WC which is fixed last month. our system is unable to synced items which were sold on repairdesk before this fix go live. so she need to manual update these items on WC or she can delete all trade in item from WC and then click on sync manual item button on repairdesk."

I hope it will be helpful. 

Usman Ali.

**Comment by JessicaSOS** [comment]
Yes I know. I erased everything and did manual setup. I am waiting for a customer to test.

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 29 août 2018 01:31
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Sync woo commerce with repairdesk (#400)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

Please find developer feedback:-

"Trade in items only synced when they are in stock or when they are sold. after sale it doesn't synced with WC. as i said earlier there was a bug when trade in item sold on repairdesk it doesn't update it on WC which is fixed last month. our system is unable to synced items which were sold on repairdesk before this fix go live. so she need to manual update these items on WC or she can delete all trade in item from WC and then click on sync manual item button on repairdesk."

I hope it will be helpful.

Usman Ali.

**Comment by JessicaSOS** [comment]
Oh my god, it seems to be settled! I have tests with some items and it works! Thank you ! However, it is important to note that once the item is online, only a sales transaction will allow the item to withdraw from our website. If we change the status manually for "sold", "scrapped for parts", or any other custom or default status, the item will stay online.

**Comment by usmanalikhan93** [comment]
@JessicaSOS 

Acknowledged.
