### ISSUE TITLE
Sale price in trade in ticket

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#434]
All tradein tickets we create are now with the sale price. This was not the case last week. I do not know what you touched, but it should be returned to normal please. It is not supposed to have any selling price in a tradein ticket.

_French:
Tous les billets tradein que nous créons sont maintenant avec le prix de vente. Ce n'était pas le cas la semaine dernière. Je ne sais pas a quoi vous avez touché, mais il faudrait le remettre à la normal svp. Il n'est pas suposé avoir aucun prix de vente dans un billet tradein._

**Comment by JessicaSOS** [comment]
tnx

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 6 septembre 2018 02:20
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Sale price in trade in ticket (#434)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

Your reported issue has been assigned to development team and I hopefully it will be fixed early next week.
Your patience would be highly appreciated.

Thanks!
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali.

**Comment by JessicaSOS** [comment]
Can you test before mentioning that it is corrected. It is not the case at all. Thank you for reopening this task.

**Comment by JessicaSOS** [comment]
Not fixed, please test it

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 12 septembre 2018 10:11
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Sale price in trade in ticket (#434)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked again but it seems to work fine. Can you explain this through screenshot ?

**Comment by JessicaSOS** [comment]
I made a video but I am not able to send it via this platform. please ask Ali or add any repair task in a trade in ticket and you will see!

**Comment by usmanalikhan93** [comment]
ok @JessicaSOS

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have seen your video, it looks like you are confusing in task price and trade in price. When you add a task in trade in ticket, it displays the task price. 
If you still find any confusion do contact Ali Hassan. Or you can explain me the scenario. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
I have not received a video ...
The price of the stain was never displayed during a trade in a few weeks ago. Recently, the regular selling price is displayed.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Sorry I just missed this. I have figured one scenario in which this issue exists. So I have reported to our dev team. Hopefully it will be fixed in next week.

**Comment by usmanalikhan93** [comment]
Hi again @JessicaSOS  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by JessicaSOS** [comment]
It seems to be corrected. Thank you very much.
