### ISSUE TITLE
Purchase Order Search for Items Doesn't Work with Multi SKU

### ISSUE THREAD

**Issue by serfma** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#471]
If you use multiple SKU for your parts, you will be unable to search for them in purchase orders after you select a supplier. 
![image](https://user-images.githubusercontent.com/1673121/46907287-488c0e80-cede-11e8-87e9-b8a26606c4a7.png)

As you can see here, I have an item for a white iPhone 6, using multiple SKU and search cannot find it.
![image](https://user-images.githubusercontent.com/1673121/46907291-60fc2900-cede-11e8-9ffb-43344ad6eacd.png)

**Comment by usmanalikhan93** [comment]
Sure thing @serfma . Let me take a look at this and revert back in 6-12 hours. I will reach out to you if I need more information.

**Comment by usmanalikhan93** [comment]
Hi @serfma 

I hope you are doing well. Purchase order search works on supplier you have selected. If you have selected a supplier, it will only search those item which are belongs to that supplier.

**Comment by serfma** [comment]
> Hi @serfma
> 
> I hope you are doing well. Purchase order search works on supplier you have selected. If you have selected a supplier, it will only search those item which are belongs to that supplier.

I see you moved this to Week 4, does this mean you understand what the issue is and are working on it? It sounded like the problem was misunderstood so I wanted to verify as it very much is a headache still.

**Comment by usmanalikhan93** [comment]
Hey @serfma 

Sorry for the delay. Just an update we have fixed reported issue and it’s available for beta testing on sandbox server. We are hoping to go live with this either today or tomorrow hopefully. I will let you know once it will be live.

**Comment by usmanalikhan93** [comment]
Hi @serfma 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again @serfma  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks 
Usman Ali

**Comment by serfma** [comment]
I'm going to update this issue as this is the official location you guys want to track bug reports.

As on 11/28/2018 it is not fixed. It does let you search by SKU, but not by name, regardless what supplier you're set to.

**Comment by usmanalikhan93** [comment]
Hi @serfma 

Just an update we have fixed reported issue and it’s available for beta testing on sandbox server. We are hoping to go live with this today. I will update you once it will be available on live server.

**Comment by usmanalikhan93** [comment]
Hi @serfma 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
