### ISSUE TITLE
Tax Problem not fixed yet (TVQ)

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#486]
Hello,
This problem is not really recent. It has already been postponed several times. There is an improvement each time, but it is never corrected in full. We still have problems with taxes. They default, but when we modify the notes or add an item, the amounts do not correspond to reality. Only the GST puts it. The calculation of the QST no longer works. Also, when we convert a lead into a ticket, the QST is also in error. It should be corrected quickly because several errors have appeared and obviously, employees do not pay attention to the amount of taxes!

_--
french:
Bonjour,
Ce problème n'est vraiment pas récent. Il a déjà été reporté plusieurs fois. Il y a une amélioration a chaque fois, mais ce n'est jamais corrigé en entier. Nous avons encore des problèmes avec les taxes. Elles se mettent par défaut, mais lorsque nous modifions le billets ou que nous ajoutions un item, les montants ne correspondent pas à la réalité. Uniquement la TPS ce met. Le calcul de la TVQ ne fonctionne plus. Aussi, lorsque nous convertissons un lead en billet, la TVQ est également en erreur. Il faudrait corrigé rapidement car plusieurs erreur sont apparu et évidemment, les employés ne portent pas attention au montant des taxes!_

**Comment by usmanalikhan93** [comment]
Sure thing @JessicaSOS . Let me take a look at this and revert back in 12-24 hours. I will reach out to you if I need more information.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up . 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
It seems to work well in a ticket. On the other hand, when we modify a lead by adding a second task, there is still a problem with the QST. I have not tested converting a lead into a ticket yet ...

**Comment by usmanalikhan93** [comment]
Ok let me check this.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi again @JessicaSOS - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by JessicaSOS** [comment]
Hello,
Sorry for the response time I was on vacation. This problem actually seems to be fixed.
Thank you !

**Comment by JessicaSOS** [comment]
if we enter a price manually in a lead, the TVQdoes not register.
Please reopen, :(
--

si nous entrons un prix manuellement dans un lead, la TVQ ne s'inscrit pas.
merci de réouvrir cette tâche

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Can you send me a video of this issue please ?

**Comment by JessicaSOS** [comment]
Video of tax problem in lead attached

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 20 février 2019 01:55
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Tax Problem not fixed yet (TVQ) (#486)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

Can you send me a video of this issue please ?

**Comment by JessicaSOS** [comment]
I sent you the video by email because here I am not able to send it.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I didn't receive any video in email. Can you send me again ?

**Comment by JessicaSOS** [comment]
I sent you the video by email because here I am not able to send it.

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 20 février 2019 01:55
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Tax Problem not fixed yet (TVQ) (#486)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

Can you send me a video of this issue please ?

**Comment by JessicaSOS** [comment]
Is sending again, please let me know if you don’t received

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 26 février 2019 23:48
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Tax Problem not fixed yet (TVQ) (#486)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

I didn't receive any video in email. Can you send me again ?

**Comment by usmanalikhan93** [comment]
Naa didn't receive any video. Please send on this email address "usm.khan83@gmail.com".

**Comment by usmanalikhan93** [comment]
Got it!

**Comment by usmanalikhan93** [comment]
For internal Use:
https://repairdesk.atlassian.net/browse/REP-1518

**Comment by JessicaSOS** [comment]
Hello,
this task is not settled yet and we use more and more lead. Can you please correct.
Thank you and good day

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

It's on beta server. And we will push it on live tomorrow hopefully. If you want to check, you can test it on beta. Here is the link app.repaircrm.co

**Comment by JessicaSOS** [comment]
Taxes seem to work. I tried to enter a price manually and I tried to enter an item with a price already configured and both work. However, as much in the live version as the beta version, I am not able to put two repairs. When I want to add the repair by clicking "add to line", an error message is displayed.
See Attachment.
<img width="939" alt="unable to add a second line" src="https://user-images.githubusercontent.com/40500094/53975681-706d5000-40d3-11e9-8bc1-f0e77355d1a4.png">

_--
french:
Les taxes semble fonctionner. J'ai essayer d'entré un prix manuellement et j'ai essayer d'entré un item avec un prix déjà configurer et les deux fonctionnent. Cependant, autant dans la version live que la version beta, je ne suis pas en mesure de mettre deux réparations. Lorsque je veux ajouter la réparation en cliquant sur "ajouter à la ligne", un message d'erreur s'affiche. 
Voir pièce jointe._

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Yes you are right it gives error on second line item when adding it. It's already been reported as In House bug. I have discussed with our CTO Imran, we have planned it for next week. 

Thanks 
Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
It is indeed corrected! Thank you
It only misses the problem for the second item.
Have a good day

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1008

**Comment by JessicaSOS** [comment]
This problem had been corrected but, I noticed a file on March 14 (last Thursday) that the problem had reappeared. SOS Phone Ste-Foy Lead: L-F-20580, Coverti ticket: F-4828. Thank you for reopening this problem.
--
Ce problème avait bien été corrigé mais, j'ai remarquer un dossier le 14 mars (jeudi dernier) que le probème était réapparu. SOS Phone Ste-Foy Lead:L-F-20580, Coverti en billet: F-4828. Merci de réouvrir ce problème.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked it but it is working fine.

**Comment by JessicaSOS** [comment]
Does not work in Ste-Foy, I just tested it. See lead # L-F-20584 that I created at the moment via the widget. I did not test the other shops ...

Ne fonctionne pas à Ste-Foy, je vien de le tester. Voir lead #L-F-20584 que j'ai créé à l'instant via le widget. je n'ai pas tester les autres boutiques...

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Sorry for the inconvenience. Yes it is not working. I have checked it and yes issue exists. I have highlighted to dev team. I will inform you when it will be fix.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your both issues are now fixed. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
fixed tnx !

**Comment by JessicaSOS** [comment]
It is also fixed for the addition of a second line.
