### ISSUE TITLE
Reconciliation Report Email and SMS Issue - Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#517]
**Hi Sir,**

**Business Name / Store Name:**
Modesto | DrPhone Fix

**Customer Credentials:**
Available on Jira

OS: Windows / MacBook
Module: Cash Drawer/Shift Functionality
Configuration Setting: Correct
Roles & Permissions: Correct

**Issue:**
Ending shift not sending Reconciliation Report via SMS and Email.
 
**Steps to Reproduce Issue/Provide Video:**
1. Login to RepairDesk Test account.
2. Go to Store Settings >> Cash Register >> Notification Settings.
3. Enable triggers against SMS on Shift Close and Email On Shift Close.
4. Start the shift and do some test transactions.
5. End the shift and check email.
6. No email is found.

**Current Results:**
InHouse Testing Done. I am unable to get any email of reconciliation report once the shift is ended.

**Expected Result:**
Email and SMS should be sent automatically once we end the shift.

**Comment by hamzaakbar4444** [comment]
Hey!
it is working fine on my end.Kindly reverify at customer end.
if issue is still perisist kindly create a jira ticket and Assign it to Developer.

Thanks..

**Comment by ali-repairdesk** [comment]
Customer has been updated.

Waiting for feedback.

**Comment by ali-repairdesk** [comment]
Issue has been identified and will be fixed by end of this week.

Task reference:
https://repairdesk.atlassian.net/browse/REP-849

**Comment by usmanalikhan93** [comment]
Hi @ali-repairdesk 

Issue has been fixed. Please verify at your end.

**Comment by ali-repairdesk** [comment]
Customer has been updated.

Still waiting for feedback.

**Comment by Repair-Desk** [comment]
@usmanalikhan93 Customer is still facing the issue where he doesn't receive an email or sms when a shift is closed. Can we check this again?

**Comment by usmanalikhan93** [comment]
Hi @ali-repairdesk @Repair-Desk 

We have found that in case of employee login, Ending shift not sending Reconciliation Report via SMS and Email. I have assigned to developer. Hopefully it will be fixed soon.

**Comment by usmanalikhan93** [comment]
Hi @ali-repairdesk 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
