### ISSUE TITLE
Tradein Commission report 

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#554]
When a phone is put in a note under the "accessory / tradein" category, it is counted in commission reports as an accessory. It's the only place we can put a phone in a ticket.

See example of the clilente "Annie Bacon" and the employee's commission report "Stephanie Cloutier".

There is also the example of the client "Jocelyne Habonimana" who bought 2 accessories and 1 phone. However, Stéphanie's commission report mentions a commission of $ 14.50 corresponding to the commission rate, but only for the telephone. Accessories are not counted. Thanks for getting back to me.
<img width="932" alt="jocelyne" src="https://user-images.githubusercontent.com/40500094/50257879-3a210e00-03cb-11e9-930a-ea8bd13fb1e9.png">
<img width="934" alt="commission report" src="https://user-images.githubusercontent.com/40500094/50257887-41e0b280-03cb-11e9-8426-76bbf50dcdcb.png">

--
french:
Quand un téléphone est mis dans un billet sous la catégorie "accessoire/tradein", il est comptabilisé dans les rapports de commissions comme étant un accessoire. C'est pourtant, le seul endroit où nous pouvons mettre un téléphone dans un billet. 

Voir exemple de la clilente" Annie Bacon" et le rapport de commiion de l'employé "Stephanie Cloutier". 

Il y a aussi l'exemple de la cliente "Jocelyne Habonimana" qui acheté 2 accessoires et 1 téléphone. Pourtant, le rapport de commission de Stéphanie mentionne une commission de 14.50$ correspondant au taux de commission mais, uniquement pour le téléphone. Les accessoires ne sont pas compté. Merci de me revenir.

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS , 
Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1243

**Comment by JessicaSOS** [comment]
Do you misunderstand the problem or do you want another example?

**Comment by usmanalikhan93** [comment]
Ok let me check again.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali.

**Comment by JessicaSOS** [comment]
Thank you to reopen, it is not fixed. See image attached.

--
Merci de réouvrir, ce n'est pas réglé. Voir image en pièce jointe.

Commission report:
<img width="945" alt="stacey commission report" src="https://user-images.githubusercontent.com/40500094/53838490-3c731d00-3f63-11e9-90d2-1bced1bebea5.png">

<img width="939" alt="invoice fl-15267" src="https://user-images.githubusercontent.com/40500094/53838814-f074a800-3f63-11e9-95d4-839ec95d5f49.png">

xxx7810:
<img width="938" alt="trade in 11861" src="https://user-images.githubusercontent.com/40500094/53838795-e783d680-3f63-11e9-8a4b-4b94c7568dfc.png">

<img width="929" alt="fl-15267 appear in commission report" src="https://user-images.githubusercontent.com/40500094/53839055-91fbf980-3f64-11e9-8734-a1b9ae6d77b8.png">

<img width="939" alt="setting trade in stacey" src="https://user-images.githubusercontent.com/40500094/53839290-27978900-3f65-11e9-9447-51598c9ea570.png">

**Comment by usmanalikhan93** [comment]
OK Let me check.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have drilled down your issue and yes issue exists. Now I have scheduled this in next week with it's developer. Then we will try to reproduce the case which is causing this issue. I will update you once the issue is fix. 

For internal use:
https://repairdesk.atlassian.net/browse/REP-1628

**Comment by JessicaSOS** [comment]
ok tnx to let me know

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. I have identified one case in which it was causing this issue. Now this issue has been fixed. Please verify at your end and do let us know if you have question. 

Thanks!
Usman Ali.

**Comment by JessicaSOS** [comment]
Is it settled from what date? Does this correct commissions before that date too?
Because the invoice FL-15267 of SOS Phone Limoilou shows us that the problem is still present.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

It was fixed on 29 march 2019. No it will not correct the commission for old dates.
