### ISSUE TITLE
Ticket label Template editor working

### ISSUE THREAD

**Issue by brazelab** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#620]
It is impossible to use the ticket label template editor to get a working template.
Changes are not saved properly and tags are not working.

A simple test shows the problem with the editor.
1. edit the ticket label
2. change nothing and save the ticket.
3. preview the ticket and you will see there is data missing.

Reorganizing the tags makes the problem even worse, the labels are no longer organised by device and run over multiple labels.

**Comment by Repair-Desk** [comment]
**@brazelab** 

Hey Adeel, Usman here 👋 Sure thing! Let us take a look to see if we're getting the same issue as you and I'll circle back to you.

FYI, we're working on a new label design and you can checkout the thread here: @ #569 

@usmanalikhan93 Please check this early next week

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1235

**Comment by usmanalikhan93** [comment]
Hi @brazelab 

I hope you are doing well. Please find QA feedback on this: 

"The Actual problem is that customer name Tag is not working/displaying when user preview that ticket label after edit 
Steps:
1-Go to Ticket label and edit tag and save it 
2- preview that ticket label tag from there (Template Editor-->Ticket label)
3-customer name tag is not working there

But if user print it from any ticket it is working there only issue is when user preview it from template editor"

Is this the issue you were facing ?

**Comment by brazelab** [comment]
<img width="296" alt="after edit" src="https://user-images.githubusercontent.com/46997379/51918726-5a88b300-23e2-11e9-85fe-6a31e19e044a.PNG">
<img width="289" alt="original" src="https://user-images.githubusercontent.com/46997379/51918728-5a88b300-23e2-11e9-8104-a97111c190b6.PNG">


It shows incorrectly in the editor preview and the print preview,

I have tried to open the new template in the topic linked usman, however the doc link has expired.

**Comment by usmanalikhan93** [comment]
Hi @brazelab  

Sorry for the continued inconvenience. We have fixed this issue and it is on demo server. We are expecting to go live with this in current week release. I will update you once it will be available on live server. 
Thanks for the patience. 
Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi @brazelab 

Sorry for the delay. I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by brazelab** [comment]
Not entirely solved, see attached screenshot. Labels don't organize themselves when there are multiple devices.

<img width="280" alt="repairdesk ticket" src="https://user-images.githubusercontent.com/46997379/52471432-299e4000-2b91-11e9-9740-f5bc95ce8eaa.png">

**Comment by usmanalikhan93** [comment]
@brazelab what size you are using ? Are you using code 128 ?

**Comment by brazelab** [comment]
<img width="650" alt="label siz" src="https://user-images.githubusercontent.com/46997379/52476432-e054ed00-2b9e-11e9-82d1-cd9a02ff77b4.PNG">

**Comment by brazelab** [comment]
Hi RD team,

Can you please confirm that you are not seeing the incorrect label printing issues

**Comment by usmanalikhan93** [comment]
Hi @brazelab 

Danish will contact you and he will resolve your issue regarding ticket label.
