### ISSUE TITLE
Multiple Issue with RMA | Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#633]
**Hi Sir,**

**Business Name:**
Modesto | DrPhone Fix

**Store Name:**
Coral Spring

**Module:**
RMA

**Configuration Setting:** Correct
**Roles & Permissions:** Correct

Issue:
Customer is facing an issue that once we search for RMA-031. You will see the Submitted Date as 28 Dec, 2019. Once I edit it and make it 2018, it still goes back to 2019.

For the very same reason if we apply the filter dated 28th Dec till 20th Jan, RMA-031 doesn't show up in search results.

I am attaching relevant screenshots for the assistance.
![edit-goes back](https://user-images.githubusercontent.com/26381305/51909614-e30d5080-23ee-11e9-9f1d-9a6d23cddf45.jpg)
![rma not in search results](https://user-images.githubusercontent.com/26381305/51909615-e30d5080-23ee-11e9-95a1-659c19c4f9e3.jpg)
![wrong date-rma](https://user-images.githubusercontent.com/26381305/51909616-e30d5080-23ee-11e9-93a5-3f0c35c932e7.jpg)

**Current Results:**
Some issues are being observed in RMA.

**Expected Result:**
RMA module should work without any issues.

**Comment by usmanalikhan93** [comment]
For internal use
https://repairdesk.atlassian.net/browse/REP-1282

**Comment by usmanalikhan93** [comment]
Hi @ali-repairdesk 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by ochoaonline** [comment]
![rma 2](https://user-images.githubusercontent.com/35181467/52593785-d689ee80-2e17-11e9-860d-10ea00bc50b1.png)

Just checked the RMA, the submitted or returned on dates are still showing up blank on the main screen can this be fixed

**Comment by usmanalikhan93** [comment]
Hi @ochoaonline  

Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

For internal use:
https://repairdesk.atlassian.net/browse/REP-1370

**Comment by ochoaonline** [comment]
Your welcome
