### ISSUE TITLE
Serialized Merchandise issue 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#915]
Hello, 

Serialized merchandise once selected to be used on a repair, isn't been marked as used on the inventory section. The quantity goes down to what we have instock but the serial number(s) won't get marked as used and they remain as if they were in stock. I have take a video of the issue. I will send it via chat to one fo the reps. Or if theirs an email where I can send it to let me know. Thank you.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I hope you are doing well. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

You can send the video on fahad@repairdesk.co.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I have checked your concern and when I add serialized part with repair and made its ticket, then it does marked as used. Can you please check again on your side and let me know if you still face issue. 

Thanks 
Usman Ali

**Comment by Omar1892** [comment]
Hello, thank you for getting back to me. When we do an inventory check every week it will do it on some random parts. But theirs always 1 that isn't marked at used or some times 2 - 3 items. It might not do it on 1 part you would have to do it on a bunch of inventory for it to do it. But this issue has being happening for a long time. But as you can see in the video its happening.

**Comment by fahadimran303** [comment]
Hello @usmanalikhan93 ,

Please check the video below:
https://drive.google.com/file/d/1FWMKBZJjuz-uH2-PvQPwQhZJHcy4eT-n/view

**Comment by usmanalikhan93** [comment]
Thanks @fahadimran303 

I will check and try to reproduce in my test account.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by Omar1892** [comment]
ill let you know if it happens again with in the next couple of days/weeks. Thank you.

**Comment by Omar1892** [comment]
Hello, 

The issues is still happening. As you can see in the picture we have 1 item in stock and ill explain why in a sec. The system is showing us that we have (0) items in stock with 2 serial number that haven't been used. When we checked our inventory on hand we have 1 item in-stock and still 2 serial numbers in-stock, so I checked the serial number history and it says that the 0015258 serial number has already been used but it wasn't removed from the system automatically after it was marked as used. Than it shows that it went back in stock for some reason but when I checked the repair ticket it shows that it was used on the repair assigned to. We manually added the item back in to the in-stock since it was missing from the inventory. 

![Screen Shot 2019-09-16 at 11 46 55 AM](https://user-images.githubusercontent.com/47898011/64984490-d6534500-d877-11e9-81fe-bde737e6b331.png)
0015259 its still in-stock with 1 item in our inventory. 
![Screen Shot 2019-09-16 at 11 39 50 AM](https://user-images.githubusercontent.com/47898011/64984182-14039e00-d877-11e9-9dc0-0e348c0d9720.png)

**Comment by MuhammadAdnan32** [comment]
Hey Omar1892, 
 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you. Thank you

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892,
I have reproduced the same case on my test account and I have also review your admin history. We have allowed creating a ticket from POS with In-stock Zero. When we create ticket from POS and attach part on hand quantity goes 0 to -1. In your case, you use serial and then you created a ticket from POS with the same part and delete the serialized part from the ticket which makes you on hand zero with one serialized item. That's why you have on hand zero with one serialized item and -1 item is available to serialized.
![Serial_case_issue](https://user-images.githubusercontent.com/50608942/65038616-cae04680-d969-11e9-85f1-8909e5df847b.png)

Thanks

**Comment by Omar1892** [comment]
Hi, I don't understand stand the explanation. Is there any way I can get a call? This issue just got repeated on another inventory item. This happens a lot in my inventory.

**Comment by Omar1892** [comment]
The issue with the inventory been incorrectly and the serialized merchandise not been removed once the product are used are still happening. The issue right now is that the system is showing that we have 0 items in stock and 1 item serialized. We do have 1 item instock but it shows as zero, and the serial number is correct we do have that serial number instock. 
![Screen Shot 2019-09-23 at 10 35 05 AM](https://user-images.githubusercontent.com/47898011/65448863-9f88ac00-ddee-11e9-9318-800b2110a9b3.png)
![Screen Shot 2019-09-23 at 10 35 15 AM](https://user-images.githubusercontent.com/47898011/65448865-a1526f80-ddee-11e9-909d-1f9de3eac509.png)

**Comment by usmanalikhan93** [comment]
@MuhammadAdnan32 can you please update on this ?

**Comment by MuhammadAdnan32** [comment]
@usmanalikhan93 Issue has been explained to Fahad Bhai and he contacted the customer on live chat. We are closing this task.
