### ISSUE TITLE
invoice not able to display foreign characters

### ISSUE THREAD

**Issue by gijoe911** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#958]
we have an issue with the invoice not able to display chinese characters. can u please look into that?

![WeChat Image_20191114120618](https://user-images.githubusercontent.com/25240657/68826154-a25d9a00-06d7-11ea-8cdf-752d0ccdf2c7.jpg)

**Comment by afnanforex** [comment]
Hello @gijoe911
 
Sorry for the trouble. As i have tested it on testing account it is working fine. I need to test it to your account.
Please share your repairdesk account login details so i can verify it on your account as well.
You can share your login details at afnan@repairdesk.co

I will update you as soon as i have more info on it. 

Regards,
Afnan

**Comment by gijoe911** [comment]
Hi Afnan, credentials sent.

**Comment by Afnan-Mahmood** [comment]
Thank you @gijoe911 for sharing details. 

Let me check it. I will circle back to you as soon as i have more info on it.

**Comment by Afnan-Mahmood** [comment]
Hello @gijoe911 

As your issue has been resolved according to whats app discussion. Now the invoice is working fine as earlier on iPhone and web as well.
![3CDF399D-731D-46A0-AFFD-7F6AD01E811D](https://user-images.githubusercontent.com/55185653/68835597-3c264680-06da-11ea-840f-989ea13255f5.jpg)

**Comment by gijoe911** [comment]
seems like the issue is still there if email is sent by the system.. looks like something is wrong with the embedded pdf generator. please check

**Comment by Afnan-Mahmood** [comment]
Hello joe,

Hope you are doing well
You request is forwarded to developmemt team. They are working on it. Once
we are able to reproduce the bug in our testing enviourment we will fix
this on priority basis.

Best,
Afnan

**Comment by gijoe911** [comment]
checked again today with another customer. the same issue is still there. please fix it asap

![image](https://user-images.githubusercontent.com/25240657/68992032-c7e9cf80-08a0-11ea-8cd0-4d8d18aeb125.png)

**Comment by Afnan-Mahmood** [comment]
Hello joe

Sorry the trouble
Issue is forwarded to our development team. I will update as soon as issue
will be fixed.

Best,
Afnan

**Comment by Afnan-Mahmood** [comment]
Hello @gijoe911 

I want to update you regarding the issue we tried to reproduce this issue at our end from system and iphone as well but unfortunately issue was not reproduced at out testing and development environment. We are really sorry for this as until issue not reproduced at our end we can't resolve it.
Issue is not on every pdf it's very rare so there can be any other conflict which is not related to the system.
If you have any solid scenario with which you can update us with the steps by which this issue can be reproduced than we are happy to resolve this once issue is there.

Best,
Afnan

**Comment by gijoe911** [comment]
I can try to send u an invoice on my end to an email of yours and see if u get the same error. can u please share email to send to?

**Comment by Afnan-Mahmood** [comment]
You can share email on afnan@repairdesk.co
I already checked from your account by sending email to myself but issue not reproduced. PDF which I receive showing terms and conditions correctly. We can try to reproduce it if reproduced we will solve this for sure on priority basics.

**Comment by gijoe911** [comment]
i've sent u a pdf invoice. looks like the issue is still there per our whatsapp conversation. please check and get back to us. it looks like it's happening to all of our invoices so this requires your urgent attention. thanks

**Comment by Afnan-Mahmood** [comment]
Hello @gijoe911 

Hope you are doing well.

As per our whatssapp discussion your issue which is related to IPad app has been fixed. Please verify at your end. Hope it works for you as well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Best,
Afnan

**Comment by usmanalikhan93** [comment]
Hi @gijoe911 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
